# -*- coding: utf-8 -*-
"""discovery_appv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFrEKzSFqMt__ilaA8_rYzx3EE1LN5n7
"""

# Install Streamlit if not already installed
!pip install streamlit

import json
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
import streamlit as st
from openai import OpenAI

# Set Streamlit Page Configuration
st.set_page_config(page_title="Shopify Discovery Assistant", page_icon="🛍️", layout="wide")

MODEL_NAME = "meta-llama/Llama-3.3-70B-Instruct:together"

session = requests.Session()

# Popular Shopify Stores
POPULAR_SHOPIFY_STORES = [
    "gymshark.com", "allbirds.com", "kith.com", "fabletics.com",
    "aloyoga.com", "chubbieshorts.com", "rothys.com", "taylormade-golf.com",
    "cotopaxi.com", "vuoriclothing.com", "rhone.com", "marine-layer.com",
    "mottandbow.com", "bombas.com", "noble-apparel.com", "unTuckit.com",
    "brooklinen.com", "outerknown.com", "tentree.com", "blundstone.com", "tuckernuck.com"
]

EXIT_INTENTS = [
    "exit", "quit", "bye", "goodbye", "good bye",
    "no need now", "no need", "stop", "close"
]

def parse_user_prompt(user_prompt: str):
    query = user_prompt
    max_price = None
    price_match = re.search(r"under\s*\$?(\d+(?:\.\d+)?)", user_prompt, re.IGNORECASE)
    if price_match:
        max_price = float(price_match.group(1))
        query = re.sub(r"under\s*\$?(\d+(?:\.\d+)?)", "", query, flags=re.IGNORECASE).strip()
    return query, max_price, None, None, None

SYSTEM_PROMPT = """You are an expert personal shopping assistant.

Tool Triggering Rules:
- ALWAYS invoke `search_shopify_dynamic` when the user expresses intent to find, buy, search for, or browse products.
- Clean the user's input by stripping out conversational fluff.
"""

tools = [
    {
        "type": "function",
        "function": {
            "name": "search_shopify_dynamic",
            "description": "Searches popular Shopify stores for items.",
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "Cleaned search query keywords.",
                    }
                },
                "required": ["prompt"],
            },
        },
    }
]

def fetch_store_products(store: str, query: str, max_price: float = None) -> list:
    """Fast single-store worker with strict 1.2s timeout."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    api_url = f"https://{store}/search/suggest.json?q={query}&resources[type]=product&resources[limit]=10"
    matched_products = []

    try:
        res = session.get(api_url, headers=headers, timeout=1.2)
        if res.status_code != 200:
            return matched_products

        products = res.json().get("resources", {}).get("results", {}).get("products", [])

        for prod in products:
            title = prod.get("title", "")
            price = float(prod.get("price", 0.0))
            raw_desc = prod.get("body") or prod.get("summary") or "No description provided."
            clean_desc = re.sub(r"<[^>]+>", "", raw_desc).strip()[:100] + "..."

            if max_price and price > max_price:
                continue

            image_url = prod.get("image") or prod.get("featured_image", {}).get("src")
            if image_url:
                if image_url.startswith("//"):
                    image_url = f"https:{image_url}"
                elif not image_url.startswith("http"):
                    image_url = f"https://{store}/{image_url.lstrip('/')}"

            raw_url = prod.get("url", "")
            product_url = f"https://{store}{raw_url}" if raw_url.startswith("/") else raw_url

            matched_products.append({
                "title": title,
                "price": f"${price:.2f}",
                "brand": store,
                "description": clean_desc,
                "url": product_url,
                "image_url": image_url
            })
    except Exception:
        pass

    return matched_products

def search_shopify_dynamic(prompt: str = "") -> list:
    """Parallel multi-store search executor."""
    query, max_price, _, _, _ = parse_user_prompt(prompt)
    all_matched_products = []

    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = [
            executor.submit(fetch_store_products, store, query, max_price)
            for store in POPULAR_SHOPIFY_STORES
        ]
        for future in as_completed(futures):
            results = future.result()
            if results:
                all_matched_products.extend(results)

    all_matched_products.sort(key=lambda x: float(x["price"].replace("$", "")))
    unique_brand_products, seen_stores = [], set()

    for item in all_matched_products:
        if item["brand"] not in seen_stores:
            seen_stores.add(item["brand"])
            unique_brand_products.append(item)
            if len(unique_brand_products) == 6:
                break

    return unique_brand_products

def display_carousel_html(products: list) -> str:
    """Generates the HTML carousel string for rendering directly in Streamlit."""
    if not products:
        return "<p>No matching products found.</p>"

    cards_html = ""
    for item in products:
        img_src = item.get("image_url") or "https://via.placeholder.com/200x200?text=No+Image"
        cards_html += f"""
        <div style="flex: 0 0 220px; width: 220px; border: 1px solid #e0e0e0; border-radius: 12px; padding: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); font-family: sans-serif; display: flex; flex-direction: column; justify-content: space-between; background: #fff;">
            <div>
                <div style="width: 100%; height: 180px; overflow: hidden; border-radius: 8px; margin-bottom: 10px; background: #f9f9f9; display: flex; align-items: center; justify-content: center;">
                    <img src="{img_src}" style="width: 100%; height: 100%; object-fit: cover;" alt="{item['title']}">
                </div>
                <div style="font-size: 11px; text-transform: uppercase; color: #888; font-weight: bold; margin-bottom: 4px;">{item['brand']}</div>
                <a href="{item['url']}" target="_blank" style="font-size: 14px; font-weight: 600; color: #111; text-decoration: none; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; height: 36px; margin-bottom: 6px;">
                    {item['title']}
                </a>
                <div style="font-size: 16px; font-weight: bold; color: #2e7d32; margin-bottom: 8px;">{item['price']}</div>
            </div>
            <a href="{item['url']}" target="_blank" style="display: block; text-align: center; background: #000; color: #fff; padding: 8px 0; border-radius: 6px; text-decoration: none; font-size: 12px; font-weight: bold;">
                View Product
            </a>
        </div>
        """

    carousel_html = f"""
    <div style="display: flex; gap: 16px; overflow-x: auto; padding: 10px 5px; width: 100%; box-sizing: border-box; scroll-behavior: smooth;">
        {cards_html}
    </div>
    """
    return carousel_html


# ==========================================
# Streamlit Interface Implementation
# ==========================================

st.title("🛍️ Personal Shopping Assistant")
st.write("Search across 20+ top Shopify brands simultaneously!")

# Helper Function to Reset State (Re-opening / Restarting Session)
def reset_session():
    st.session_state.messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "assistant", "content": "Hi! What can I help you find today?", "products": []}
    ]
    st.session_state.session_closed = False

# Session Initialization (Runs when user opens/refreshes the link)
if "session_closed" not in st.session_state:
    st.session_state.session_closed = False

if "messages" not in st.session_state:
    reset_session()

# Prompt for Hugging Face Token before proceeding
hf_token = st.sidebar.text_input("Enter Hugging Face Token:", type="password", key="hf_token_input")

if not hf_token:
    st.warning("🔑 Please enter your Hugging Face Token in the sidebar to start the chat session.")
    st.stop()

# Initialize OpenAI client with user's input token
client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=hf_token,
)

# Sidebar Control to restart if user wants to open session manually
with st.sidebar:
    st.header("Session Status")
    if st.session_state.session_closed:
        st.warning("Session Closed")
        if st.button("🔄 Start New Session"):
            reset_session()
            st.rerun()
    else:
        st.success("Bot Active")
        if st.button("❌ End Session"):
            st.session_state.session_closed = True
            st.rerun()

# If Session is Active, Render Chat Interface
if not st.session_state.session_closed:

    # Display Chat History
    for message in st.session_state.messages:
        if message["role"] == "system":
            continue
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if message.get("products"):
                carousel_code = display_carousel_html(message["products"])
                st.components.v1.html(carousel_code, height=330, scrolling=True)

    # Input Field (Always Active)
    if user_input := st.chat_input("Ask for items (e.g., 'Find running shoes under $100')..."):

        # Check for User Close Intent
        cleaned_input = user_input.strip().lower()
        if any(intent in cleaned_input for intent in EXIT_INTENTS):
            st.session_state.messages.append({"role": "user", "content": user_input})
            st.session_state.messages.append({
                "role": "assistant",
                "content": "Happy shopping! Session closed. Re-open the page or click 'Start New Session' in the sidebar anytime.",
                "products": []
            })
            st.session_state.session_closed = True
            st.rerun()

        # Append User Message
        st.session_state.messages.append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        # Prepare trimmed context for fast execution
        system_msg = st.session_state.messages[0]
        conversation = [m for m in st.session_state.messages[1:] if m.get("content")]
        trimmed_conversation = conversation[-6:]
        payload_messages = [system_msg] + [{"role": m["role"], "content": m["content"]} for m in trimmed_conversation]

        with st.chat_message("assistant"):
            with st.spinner("Searching popular stores..."):
                try:
                    response = client.chat.completions.create(
                        model=MODEL_NAME,
                        messages=payload_messages,
                        tools=tools,
                        tool_choice="auto"
                    )
                    assistant_message = response.choices[0].message
                    products = []

                    if assistant_message.tool_calls:
                        for tool_call in assistant_message.tool_calls:
                            if tool_call.function.name == "search_shopify_dynamic":
                                args = json.loads(tool_call.function.arguments)
                                products = search_shopify_dynamic(**args)

                        reply_text = f"Here are top matching results for **'{user_input}'**:" if products else "I couldn't find matches under that criteria."
                        st.markdown(reply_text)

                        if products:
                            carousel_code = display_carousel_html(products)
                            st.components.v1.html(carousel_code, height=330, scrolling=True)

                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": reply_text,
                            "products": products
                        })
                    else:
                        reply_text = assistant_message.content
                        st.markdown(reply_text)
                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": reply_text,
                            "products": []
                        })

                except Exception as e:
                    st.error(f"Error executing search request: {e}")

else:
    # Closed Session Screen
    st.info("👋 **Session Ended.** Your chat session is closed.")
    st.write("To start a new session, re-open/refresh the Streamlit link or click **'Start New Session'** in the sidebar.")