# -*- coding: utf-8 -*-
"""discovery_appv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFrEKzSFqMt__ilaA8_rYzx3EE1LN5n7
"""

import json
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
import streamlit as st
from openai import OpenAI

import json
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
import streamlit as st
from openai import OpenAI
from duckduckgo_search import DDGS

# ==========================================
# Streamlit Page Configuration
# ==========================================
st.set_page_config(
    page_title="Shopify Discovery Assistant", page_icon="🛍️", layout="wide"
)

MODEL_NAME = "meta-llama/Llama-3.3-70B-Instruct:together"

session = requests.Session()

# Popular Shopify Stores
POPULAR_SHOPIFY_STORES = [
    "gymshark.com",
    "allbirds.com",
    "kith.com",
    "fabletics.com",
    "aloyoga.com",
    "chubbieshorts.com",
    "rothys.com",
    "taylormade-golf.com",
    "cotopaxi.com",
    "vuoriclothing.com",
    "rhone.com",
    "marine-layer.com",
    "mottandbow.com",
    "bombas.com",
    "noble-apparel.com",
    "unTuckit.com",
    "brooklinen.com",
    "outerknown.com",
    "tentree.com",
    "blundstone.com",
    "tuckernuck.com",
]

EXIT_INTENTS = [
    "exit",
    "quit",
    "bye",
    "goodbye",
    "good bye",
    "no need now",
    "no need",
    "stop",
    "close",
]

# Supported product categories for strict intent enforcement
CATEGORY_KEYWORDS = {
    "t-shirt": ["t-shirt", "tshirt", "tee", "tees"],
    "towel": ["towel", "towels", "washcloth"],
    "slippers": ["slipper", "slippers", "slides", "sandals"],
    "shorts": ["shorts", "short"],
    "pants": ["pants", "trousers", "jeans", "joggers", "leggings"],
    "shoes": ["shoes", "sneakers", "boots", "footwear"],
    "jacket": ["jacket", "coat", "outerwear", "parka"],
    "gymwear": ["gymwear", "activewear", "workout", "fitness", "gym", "sportswear"],
}


def parse_user_prompt(user_prompt: str):
    """Extracts search constraints: query terms, max price, gender, target brand, target category, and unlisted brand flag."""
    query = user_prompt
    max_price = None
    gender = None
    target_brand = None
    category = None
    is_external_brand = False

    # Price parsing
    price_match = re.search(
        r"under\s*\$?(\d+(?:\.\d+)?)", user_prompt, re.IGNORECASE
    )
    if price_match:
        max_price = float(price_match.group(1))
        query = re.sub(
            r"under\s*\$?(\d+(?:\.\d+)?)", "", query, flags=re.IGNORECASE
        ).strip()

    # Gender intent extraction
    if re.search(
        r"\b(women|womens|female|woman|ladies)\b", user_prompt, re.IGNORECASE
    ):
        gender = "female"
    elif re.search(
        r"\b(men|mens|male|man|guys)\b", user_prompt, re.IGNORECASE
    ):
        gender = "male"

    # Category intent extraction
    for cat_key, synonyms in CATEGORY_KEYWORDS.items():
        if any(
            re.search(rf"\b{re.escape(syn)}\b", user_prompt, re.IGNORECASE)
            for syn in synonyms
        ):
            category = cat_key
            break

    # Smart Brand Detection: Check Popular Shopify list
    for store in POPULAR_SHOPIFY_STORES:
        brand_name = store.split(".")[0].lower()
        if re.search(rf"\b{re.escape(brand_name)}\b", user_prompt, re.IGNORECASE):
            target_brand = store
            break

    # Smart Brand Detection: Check for explicit brand intent outside the list (e.g., Nike, Adidas, Puma)
    if not target_brand:
        explicit_brand_match = re.search(
            r"\b(brand\s+([a-zA-Z0-9]+)|([a-zA-Z0-9]+)\s+brand)\b",
            user_prompt,
            re.IGNORECASE,
        )
        if explicit_brand_match:
            extracted_brand = (
                explicit_brand_match.group(2) or explicit_brand_match.group(3)
            )
            target_brand = extracted_brand.lower()
            is_external_brand = True
        else:
            # Common major brands check
            known_external_brands = ["nike", "adidas", "puma", "under armour", "reebok", "zara", "h&m", "uniqlo"]
            for ext_b in known_external_brands:
                if re.search(rf"\b{re.escape(ext_b)}\b", user_prompt, re.IGNORECASE):
                    target_brand = ext_b
                    is_external_brand = True
                    break

    return query, max_price, gender, target_brand, category, is_external_brand


SYSTEM_PROMPT = """You are an expert personal shopping assistant.

Category & Intent Mandate Rules:
- You MUST analyze and adhere strictly to category-level intent. If the user asks for a specific category (e.g., "t-shirt"), ONLY return products belonging strictly to that category.
- Persist active user constraints (gender, explicit brand, category) across the session.
- If an explicit brand is requested by the user (e.g., "Nike"), ensure that brand is explicitly searched.

Ambiguity & Confidence Rules:
- If the user's request is vague, ambiguous, broad, or lacks concrete product detail (e.g., "show me stuff", "something cool"), DO NOT invoke any tools. Respond directly asking: "I want to help you find the right item! Could you be a bit more specific about what you are looking for (e.g., Nike gymwear, women's t-shirt)?"

Tool Triggering Rules:
- Invoke `search_shopify_dynamic` ONLY when the user expresses clear intent for a concrete product category or type.
- Clean the `prompt` parameter: strip out conversational filler and supply core query keywords along with any explicit category/gender/brand modifiers.
"""

tools = [
    {
        "type": "function",
        "function": {
            "name": "search_shopify_dynamic",
            "description": "Searches store endpoints and DuckDuckGo web search with smart intent routing.",
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "Cleaned search query keywords including active gender, brand, and category parameters.",
                    }
                },
                "required": ["prompt"],
            },
        },
    }
]


def fetch_store_products(
    store: str,
    query: str,
    max_price: float = None,
    gender: str = None,
    category: str = None,
) -> list:
    """Fast single-store worker with strict stock, gender, and category level filtering."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    api_url = f"https://{store}/search/suggest.json?q={query}&resources[type]=product&resources[limit]=10"
    matched_products = []

    target_keywords = [w.lower() for w in re.findall(r"\b\w{3,}\b", query)]

    try:
        res = session.get(api_url, headers=headers, timeout=1.2)
        if res.status_code != 200:
            return matched_products

        products = (
            res.json()
            .get("resources", {})
            .get("results", {})
            .get("products", [])
        )

        for prod in products:
            # 1. STRICT STOCK CHECK
            is_available = prod.get("available", True)
            if not is_available:
                continue

            title = prod.get("title", "")
            price = float(prod.get("price", 0.0))
            title_lower = title.lower()

            # 2. CATEGORY-LEVEL MANDATE FILTERING
            if category:
                allowed_synonyms = CATEGORY_KEYWORDS.get(category, [category])
                if not any(
                    re.search(rf"\b{re.escape(syn)}\b", title_lower)
                    for syn in allowed_synonyms
                ):
                    continue

            # 3. GENDER FILTERING
            if gender == "female":
                if any(m in title_lower for m in ["men's", "mens", "for men"]):
                    continue
            elif gender == "male":
                if any(
                    w in title_lower
                    for w in ["women's", "womens", "for women"]
                ):
                    continue

            # 4. KEYWORD FILTERING
            if target_keywords and not any(
                kw in title_lower for kw in target_keywords
            ):
                continue

            if max_price and price > max_price:
                continue

            raw_desc = (
                prod.get("body")
                or prod.get("summary")
                or "No description provided."
            )
            clean_desc = re.sub(r"<[^>]+>", "", raw_desc).strip()[:100] + "..."

            image_url = prod.get("image") or prod.get("featured_image", {}).get(
                "src"
            )
            if image_url:
                if image_url.startswith("//"):
                    image_url = f"https:{image_url}"
                elif not image_url.startswith("http"):
                    image_url = f"https://{store}/{image_url.lstrip('/')}"

            raw_url = prod.get("url", "")
            product_url = (
                f"https://{store}{raw_url}"
                if raw_url.startswith("/")
                else raw_url
            )

            matched_products.append(
                {
                    "title": title,
                    "price": f"${price:.2f}",
                    "brand": store,
                    "availability": "In Stock",
                    "description": clean_desc,
                    "url": product_url,
                    "image_url": image_url,
                }
            )
    except Exception:
        pass

    return matched_products


def fetch_duckduckgo_products(query: str, brand: str = None) -> list:
    """DuckDuckGo web search worker: performs targeted web browsing for external brand products."""
    ddg_products = []
    search_term = f"buy {brand} {query} price" if brand else f"buy {query} product price"
    try:
        with DDGS() as ddgs:
            text_results = list(ddgs.text(keywords=search_term, max_results=6))
            image_results = list(ddgs.images(keywords=f"{brand or ''} {query} product photo".strip(), max_results=6))

            for idx, result in enumerate(text_results):
                title = result.get("title", "Product")
                snippet = result.get("body", "")
                url = result.get("href", "#")

                # Extract price using regex
                price_match = re.search(r"\$\d+(?:\.\d{2})?", title + " " + snippet)
                price_str = price_match.group(0) if price_match else "Check Site"

                # Pair with corresponding image if available
                image_url = (
                    image_results[idx].get("image")
                    if idx < len(image_results)
                    else "https://via.placeholder.com/200x200?text=No+Image"
                )

                domain = brand.upper() if brand else (url.split("/")[2].replace("www.", "") if "://" in url else "Web Store")

                ddg_products.append(
                    {
                        "title": title,
                        "price": price_str,
                        "brand": domain,
                        "availability": "In Stock",
                        "description": snippet[:100] + "...",
                        "url": url,
                        "image_url": image_url,
                    }
                )
    except Exception:
        pass

    return ddg_products


def search_shopify_dynamic(prompt: str = "") -> list:
    """Smart router: If external brand (e.g., Nike) is requested, routes directly to DDG. Otherwise searches popular stores."""
    query, max_price, gender, target_brand, category, is_external_brand = parse_user_prompt(prompt)

    # Persist intent parameters into session state
    if gender:
        st.session_state.user_intent["gender"] = gender
    if category:
        st.session_state.user_intent["category"] = category
    if target_brand:
        st.session_state.user_intent["brand"] = target_brand

    shopify_matched_products = []
    ddg_matched_products = []

    # SMART ROUTING CHOICE:
    # If explicit external brand requested (e.g. Nike), route directly to DDG Web Browsing
    if is_external_brand:
        ddg_matched_products = fetch_duckduckgo_products(query=prompt, brand=target_brand)
        return ddg_matched_products[:6]

    # Standard Parallel Search (Process 1: Shopify Stores + Process 2: DuckDuckGo Fallback)
    stores_to_search = [target_brand] if (target_brand and not is_external_brand) else POPULAR_SHOPIFY_STORES

    with ThreadPoolExecutor(max_workers=25) as executor:
        shopify_futures = [
            executor.submit(
                fetch_store_products, store, query, max_price, gender, category
            )
            for store in stores_to_search
        ]
        ddg_future = executor.submit(fetch_duckduckgo_products, query=prompt)

        for future in as_completed(shopify_futures):
            res = future.result()
            if res:
                shopify_matched_products.extend(res)

        ddg_matched_products = ddg_future.result()

    all_matched_products = shopify_matched_products + ddg_matched_products

    unique_brand_products, seen_stores = [], set()
    for item in all_matched_products:
        if item["brand"] not in seen_stores:
            seen_stores.add(item["brand"])
            unique_brand_products.append(item)
            if len(unique_brand_products) == 6:
                break

    return unique_brand_products


def display_carousel_html(products: list) -> str:
    """Generates HTML carousel string including stock status badge."""
    if not products:
        return "<p>No matching products found.</p>"

    cards_html = ""
    for item in products:
        img_src = (
            item.get("image_url")
            or "https://via.placeholder.com/200x200?text=No+Image"
        )
        cards_html += f"""
        <div style="flex: 0 0 220px; width: 220px; border: 1px solid #e0e0e0; border-radius: 12px; padding: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); font-family: sans-serif; display: flex; flex-direction: column; justify-content: space-between; background: #fff;">
            <div>
                <div style="width: 100%; height: 180px; overflow: hidden; border-radius: 8px; margin-bottom: 10px; background: #f9f9f9; display: flex; align-items: center; justify-content: center;">
                    <img src="{img_src}" style="width: 100%; height: 100%; object-fit: cover;" alt="{item['title']}">
                </div>
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px;">
                    <span style="font-size: 11px; text-transform: uppercase; color: #888; font-weight: bold;">{item['brand']}</span>
                    <span style="font-size: 10px; background: #e8f5e9; color: #2e7d32; padding: 2px 6px; border-radius: 4px; font-weight: bold;">{item['availability']}</span>
                </div>
                <a href="{item['url']}" target="_blank" style="font-size: 14px; font-weight: 600; color: #111; text-decoration: none; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; height: 36px; margin-bottom: 6px;">
                    {item['title']}
                </a>
                <div style="font-size: 16px; font-weight: bold; color: #2e7d32; margin-bottom: 8px;">{item['price']}</div>
            </div>
            <a href="{item['url']}" target="_blank" style="display: block; text-align: center; background: #000; color: #fff; padding: 8px 0; border-radius: 6px; text-decoration: none; font-size: 12px; font-weight: bold;">
                View Product
            </a>
        </div>
        """

    carousel_html = f"""
    <div style="display: flex; gap: 16px; overflow-x: auto; padding: 10px 5px; width: 100%; box-sizing: border-box; scroll-behavior: smooth;">
        {cards_html}
    </div>
    """
    return carousel_html


# ==========================================
# Streamlit Interface Implementation
# ==========================================

st.title("🛍️ Personal Shopping Assistant")
st.write("Search across 20+ top Shopify brands and web stores simultaneously!")


def reset_session():
    st.session_state.messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "assistant",
            "content": "Hi! What can I help you find today?",
            "products": [],
        },
    ]
    st.session_state.user_intent = {
        "gender": None,
        "brand": None,
        "category": None,
    }
    st.session_state.session_closed = False


if "session_closed" not in st.session_state:
    st.session_state.session_closed = False

if "messages" not in st.session_state:
    reset_session()

hf_token = st.sidebar.text_input(
    "Enter Hugging Face Token:", type="password", key="hf_token_input"
)

if not hf_token:
    st.warning(
        "🔑 Please enter your Hugging Face Token in the sidebar to start the chat session."
    )
    st.stop()

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=hf_token,
)

with st.sidebar:
    st.header("Session Status")
    if st.session_state.get("user_intent"):
        st.subheader("Active Preferences")
        st.write(
            f"**Category Mandate:** {st.session_state.user_intent.get('category') or 'None'}"
        )
        st.write(
            f"**Gender:** {st.session_state.user_intent.get('gender') or 'Not specified'}"
        )
        st.write(
            f"**Brand Lock:** {st.session_state.user_intent.get('brand') or 'All Stores'}"
        )

    if st.session_state.session_closed:
        st.warning("Session Closed")
        if st.button("🔄 Start New Session"):
            reset_session()
            st.rerun()
    else:
        st.success("Bot Active")
        if st.button("❌ End Session"):
            st.session_state.session_closed = True
            st.rerun()

if not st.session_state.session_closed:

    for message in st.session_state.messages:
        if message["role"] == "system":
            continue
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if message.get("products"):
                carousel_code = display_carousel_html(message["products"])
                st.components.v1.html(carousel_code, height=330, scrolling=True)

    if user_input := st.chat_input(
        "Ask for items (e.g., 'nike brand gymwear', 'women's t-shirts under $50')..."
    ):

        cleaned_input = user_input.strip().lower()
        if any(intent in cleaned_input for intent in EXIT_INTENTS):
            st.session_state.messages.append(
                {"role": "user", "content": user_input}
            )
            st.session_state.messages.append(
                {
                    "role": "assistant",
                    "content": "Happy shopping! Session closed. Re-open the page or click 'Start New Session' in the sidebar anytime.",
                    "products": [],
                }
            )
            st.session_state.session_closed = True
            st.rerun()

        st.session_state.messages.append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        system_msg = st.session_state.messages[0]
        conversation = [
            m for m in st.session_state.messages[1:] if m.get("content")
        ]
        trimmed_conversation = conversation[-6:]
        payload_messages = [system_msg] + [
            {"role": m["role"], "content": m["content"]}
            for m in trimmed_conversation
        ]

        with st.chat_message("assistant"):
            with st.spinner("Searching stores and web..."):
                try:
                    response = client.chat.completions.create(
                        model=MODEL_NAME,
                        messages=payload_messages,
                        tools=tools,
                        tool_choice="auto",
                    )
                    assistant_message = response.choices[0].message
                    products = []

                    if assistant_message.tool_calls:
                        for tool_call in assistant_message.tool_calls:
                            if (
                                tool_call.function.name
                                == "search_shopify_dynamic"
                            ):
                                args = json.loads(tool_call.function.arguments)
                                products = search_shopify_dynamic(**args)

                        if products:
                            reply_text = f"Here are top matching results for **'{user_input}'**:"
                        else:
                            reply_text = "No results found matching your specific category, availability, and intent criteria."

                        st.markdown(reply_text)

                        if products:
                            carousel_code = display_carousel_html(products)
                            st.components.v1.html(
                                carousel_code, height=330, scrolling=True
                            )

                        st.session_state.messages.append(
                            {
                                "role": "assistant",
                                "content": reply_text,
                                "products": products,
                            }
                        )
                    else:
                        reply_text = assistant_message.content
                        st.markdown(reply_text)
                        st.session_state.messages.append(
                            {
                                "role": "assistant",
                                "content": reply_text,
                                "products": [],
                            }
                        )

                except Exception as e:
                    st.error(f"Error executing search request: {e}")
else:
    st.info("👋 **Session Ended.** Your chat session is closed.")
    st.write(
        "To start a new session, re-open/refresh the Streamlit link or click **'Start New Session'** in the sidebar."
    )

