# -*- coding: utf-8 -*-
"""query_log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSkebq-ACbUBG1TZFOU6gCryM20lobYt
"""

"""
Daily query log: a separate script for the results table.

Table `query_log` (one row per result):
    user query | result | score  (+ brand, url, price, whether it passed the
    threshold, whether it was actually displayed)

- app.py imports `log_query` and calls it after every search.
- Rows from previous days are deleted automatically: every read and write
  first runs `purge_old_records()`, so yesterday's data never survives into today.
- View the table:      streamlit run query_log.py
- Purge from cron:     python query_log.py --purge
- Print today's rows:  python query_log.py --show

This file deliberately does not import app.py: importing it would execute the
whole Streamlit UI. Instead, app.py runs the cosine-similarity scoring and
hands the scored results to log_query().
"""
import argparse
import logging
import os
import sqlite3
from contextlib import closing
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

DB_PATH = os.environ.get(
    "QUERY_LOG_DB", str(Path(__file__).resolve().with_name("query_log.db"))
)

_SCHEMA = """
CREATE TABLE IF NOT EXISTS query_log (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    query_date        TEXT NOT NULL,      -- YYYY-MM-DD (local), used for the daily purge
    queried_at        TEXT NOT NULL,      -- full timestamp
    user_query        TEXT NOT NULL,
    result_title      TEXT,               -- NULL when the query returned no results
    result_brand      TEXT,
    result_url        TEXT,
    result_price      TEXT,
    score             REAL,               -- cosine similarity vs. the query
    passed_threshold  INTEGER DEFAULT 0,  -- 1 if score > threshold
    displayed         INTEGER DEFAULT 0   -- 1 if shown in the carousel
);
CREATE INDEX IF NOT EXISTS idx_query_log_date ON query_log(query_date);
"""


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.row_factory = sqlite3.Row
    conn.executescript(_SCHEMA)
    return conn


def _today() -> str:
    return datetime.now().strftime("%Y-%m-%d")


def purge_old_records() -> int:
    """Delete every row that was not logged today. Returns the number of rows deleted."""
    with closing(_connect()) as conn:
        cur = conn.execute("DELETE FROM query_log WHERE query_date < ?", (_today(),))
        conn.commit()
        return cur.rowcount


def log_query(user_query: str, results: list, max_rows: int = 30) -> bool:
    """
    Store one searched query and its scored results.

    `results` is a list of dicts with: title, brand, url, price, score,
    passed_threshold, displayed. An empty list still logs the query itself
    (with NULL result columns) so every query typed today appears in the table.
    Never raises: a logging failure must not break the shopping app.
    """
    try:
        purge_old_records()
        now = datetime.now()
        day, stamp = now.strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d %H:%M:%S")

        rows = []
        for r in (results or [])[:max_rows]:
            rows.append(
                (
                    day,
                    stamp,
                    user_query,
                    r.get("title"),
                    r.get("brand"),
                    r.get("url"),
                    r.get("price"),
                    r.get("score"),
                    int(bool(r.get("passed_threshold"))),
                    int(bool(r.get("displayed"))),
                )
            )
        if not rows:
            rows.append((day, stamp, user_query, None, None, None, None, None, 0, 0))

        with closing(_connect()) as conn:
            conn.executemany(
                """INSERT INTO query_log
                   (query_date, queried_at, user_query, result_title, result_brand,
                    result_url, result_price, score, passed_threshold, displayed)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                rows,
            )
            conn.commit()
        return True
    except Exception as exc:  # noqa: BLE001
        logger.warning("query_log: could not write log entry: %s", exc)
        return False


def fetch_today(displayed_only: bool = False) -> list:
    """Return today's rows, newest first (older days are purged first)."""
    purge_old_records()
    sql = "SELECT * FROM query_log WHERE query_date = ?"
    if displayed_only:
        sql += " AND displayed = 1"
    sql += " ORDER BY id DESC"
    with closing(_connect()) as conn:
        return [dict(row) for row in conn.execute(sql, (_today(),)).fetchall()]


# ==========================================
# Streamlit viewer:  streamlit run query_log.py
# ==========================================
def render_page():
    import streamlit as st

    st.set_page_config(page_title="Query Log", page_icon="🗂️", layout="wide")
    st.title("🗂️ Today's Query Log")
    st.caption(
        "One row per result, with its cosine-similarity score. "
        "Rows from previous days are deleted automatically."
    )

    col_a, col_b, _ = st.columns([1, 1, 4])
    with col_a:
        st.button("🔄 Refresh")
    with col_b:
        if st.button("🗑️ Purge previous days"):
            st.toast(f"Deleted {purge_old_records()} old rows")

    only_displayed = st.checkbox("Only results that were displayed (score above threshold)")
    rows = fetch_today(displayed_only=only_displayed)

    if not rows:
        st.info("No queries logged yet today.")
        return

    st.metric("Queries logged today", len({(r["queried_at"], r["user_query"]) for r in rows}))

    table = [
        {
            "Time": r["queried_at"][11:],
            "User query": r["user_query"],
            "Result": r["result_title"] or "(no results)",
            "Brand": r["result_brand"],
            "Price": r["result_price"],
            "Score": r["score"],
            "Passed threshold": bool(r["passed_threshold"]),
            "Displayed": bool(r["displayed"]),
            "URL": r["result_url"],
        }
        for r in rows
    ]
    st.dataframe(table)


def cli():
    parser = argparse.ArgumentParser(description="Manage the daily query log.")
    parser.add_argument("--purge", action="store_true", help="delete rows from previous days")
    parser.add_argument("--show", action="store_true", help="print today's rows")
    args = parser.parse_args()

    if args.purge:
        print(f"Deleted {purge_old_records()} old rows")
    if args.show:
        for r in fetch_today():
            print(
                f"{r['queried_at']} | {r['user_query']} | "
                f"{r['result_title']} | {r['score']} | displayed={r['displayed']}"
            )
    if not (args.purge or args.show):
        parser.print_help()


def _in_streamlit() -> bool:
    try:
        from streamlit.runtime.scriptrunner import get_script_run_ctx

        return get_script_run_ctx() is not None
    except Exception:  # noqa: BLE001
        return False


if __name__ == "__main__":
    if _in_streamlit():
        render_page()
    else:
        cli()