# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DE06E3F-PPiO6zENDOxkSTCXNt-1y7i
"""

# ==========================================
# Application & Model Settings
# ==========================================
MODEL_NAME = "meta-llama/Llama-3.3-70B-Instruct:together"
BASE_URL = "https://router.huggingface.co/v1"

# ==========================================
# Popular Shopify Stores List
# ==========================================
POPULAR_SHOPIFY_STORES = [
    "gymshark.com",
    "allbirds.com",
    "kith.com",
    "fabletics.com",
    "aloyoga.com",
    "chubbieshorts.com",
    "rothys.com",
    "taylormade-golf.com",
    "cotopaxi.com",
    "vuoriclothing.com",
    "rhone.com",
    "marine-layer.com",
    "mottandbow.com",
    "bombas.com",
    "noble-apparel.com",
    "unTuckit.com",
    "brooklinen.com",
    "outerknown.com",
    "tentree.com",
    "blundstone.com",
    "tuckernuck.com",
]

# ==========================================
# Exit Intent Trigger Words
# ==========================================
EXIT_INTENTS = [
    "exit",
    "quit",
    "bye",
    "goodbye",
    "good bye",
    "no need now",
    "no need",
    "stop",
    "close",
]

# ==========================================
# Category Keyword Mappings (Supports Plurals)
# ==========================================
CATEGORY_KEYWORDS = {
    "t-shirt": ["t-shirt", "t-shirts", "tshirt", "tshirts", "tee", "tees", "shirt", "shirts"],
    "towel": ["towel", "towels", "washcloth", "washcloths"],
    "slippers": ["slipper", "slippers", "slides", "sandals"],
    "shorts": ["shorts", "short"],
    "pants": ["pants", "trousers", "jeans", "joggers", "leggings"],
    "shoes": ["shoes", "shoe", "sneakers", "sneaker", "boots", "boot", "footwear"],
    "jacket": ["jacket", "jackets", "coat", "coats", "outerwear", "parka"],
    "gymwear": ["gymwear", "activewear", "workout", "fitness", "gym", "sportswear"],
}

KNOWN_EXTERNAL_BRANDS = [
    "nike", "adidas", "puma", "under armour", "reebok", "zara", "h&m", "uniqlo"
]

# ==========================================
# System Prompts & Tool Definitions
# ==========================================
SYSTEM_PROMPT = """You are an expert personal shopping assistant.

Category & Intent Mandate Rules:
- You MUST analyze and adhere strictly to category-level intent. If the user asks for a specific category (e.g., "t-shirt"), ONLY return products belonging strictly to that category.
- Persist active user constraints (gender, explicit brand, category) across the session.
- If an explicit brand is requested by the user (e.g., "Nike"), ensure that brand is explicitly searched.

Ambiguity & Confidence Rules:
- If the user's request is vague, ambiguous, broad, or lacks concrete product detail (e.g., "show me stuff", "something cool"), DO NOT invoke any tools. Respond directly asking: "I want to help you find the right item! Could you be a bit more specific about what you are looking for (e.g., Nike gymwear, women's t-shirt)?"

Tool Triggering Rules:
- Invoke `search_shopify_dynamic` ONLY when the user expresses clear intent for a concrete product category or type.
- Clean the `prompt` parameter: strip out conversational filler and supply core query keywords along with any explicit category/gender/brand modifiers.
"""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "search_shopify_dynamic",
            "description": "Searches store endpoints and DuckDuckGo web search with smart intent routing.",
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "Cleaned search query keywords including active gender, brand, and category parameters.",
                    }
                },
                "required": ["prompt"],
            },
        },
    }
]